language: cpp
compiler:
    - gcc
    - clang
before_install:
    - add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - apt-get update -qq
install:
    - apt-get install -y
      libsfml-dev
      clang
      g++-4.8
    - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi
script:
    - mkdir -p finals/build
    - cd finals/build
    - cmake ..
    - make
    - ./test-finals
